module.exports = {
  cookie_secret: 'secrethere',
  cookie_password: 'passwordhere',
  weixinToken: 'tokenhere',
  sms_sn: 'snhere',
  sms_password: 'passwordhere',
  sms_balance: 50,
  sms_ipbalance: 5,
  port: 3000,
  guesssong_singbalance: 10,
  guesssong_guessbalance: 20,
  guesssong_chance: 0.5,
  guesssong_basic: 100,
  guesssong_sameuser: 3,
  guesssong_guesslimit: 100,
  voice_bucket: "",
  voice_user: "",
  voice_password: "",
  image_bucket: "",
  image_user: "",
  image_password: "",
  baidupush_apikey: "4MXgVcyzyotimMpmstIrX1IY",
  baidupush_secretkey: "qeKLVO2DQSq4sov0TYSAe93Z2tZ3vgTQ",
  weixinurl: "",
  ktvdataservertype: "http",
  ktvdataserver: "",
  ktvdataport: "",
  IOSPush : "http://192.168.0.2:8000"
};
